= Preface
my contribution will be explaned in `changelog` file here.
for any map that you could fine a changelog file, the map has been revisedd and appended.

maps that has been changed already:

* Persian map (see the changelog)

---

== Why this is important
I am interested in this project for some reasons:
a. First, and foremost, it could be used in accessibility
Advancements for people with special needs, which is
glorious and humanly.
b. It could benefit cultural relationships between people,
by making it easy for them to learn different languages with
unfamiliar alphabet and letter, I myself had a big problem in
learning Greek letters! 
c. It could be used in different models of screen reading, or
as a ad hoc tool when people haven't enough time to learn letters.
I'm sure early developers had many different reasons in their mind
and I am going to trust them with all.

below desciption is fron original repositoy (unedited).

= Interscript: Script conversion maps

== Introduction

This repository contains all Interscript interoperable script conversion schemes.

== Contents

Systems from these authorities are included in this repository:

* ALA-LC
* BGN/PCGN
* ICAO
* ISO
* ODNI
* UN (by UNGEGN)
* and others systems that do not have a defined authority

== Organization

All maps are encoded in the "Interoperable Script Processing Model" language syntax (extension: `.imp`).

System file names adhere to the script conversion system code convention
of ISO 24229.

== Copyright and license

This is a Ribose project. Copyright Ribose.
